# Wajib untuk semua project yang menggunakan library AndroidX (Compose, Room, Hilt, dll)
android.useAndroidX=true

# Kotlin code generation via K2/KSP tidak butuh AndroidX support library lama
android.enableJetifier=false

# Optimasi build
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
kotlin.code.style=official
